### ISSUE TITLE
Compiled binaries request

### ISSUE THREAD

**Issue by bagaturchess** [PGG106/Primer#1]
Hi and thanks for the nice project!
Is there somewhere the compiled binary version of the tool, because I have hard times compiling it?
I will highly appreciate if you upload an exe in the releases section.
Best regards,
Krasimir

**Comment by PGG106** [comment]
Hi, i could release linux binaries but i don't own a windows machine that can compile the project.
If you are interested in compiling a windows binary you can follow this guide <https://github.com/official-stockfish/Stockfish/wiki/Compiling-from-source>, on linux/wsl it just compiles out of the box by typing "make".
In the coming days i'll see if i can write a custom, easier to run, makefile instead of using sf's

**Comment by bagaturchess** [comment]
Hi and thanks for the answer!
Let me share more information.
I am using MinGW. It has mingw32-make.exe but it doesn't work - gives errors during execution.
I am trying to compile it with g++ command g++ ./src/*.cpp and it gives an error:
uci.cpp:(.text+0x1d6): undefined reference to `Stockfish::Tools::convert(std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >&)'
Maybe I miss compiler options?
Best regards,
Krasimir

**Comment by PGG106** [comment]
instead of using that, just run "make" in the same directory as the makefile

**Comment by PGG106** [comment]
If The compile still fails if you don't have a full msys2 system setup, either follow the SF guide or wait for the makefile rewrite (which might come fairly late).

**Comment by PGG106** [comment]
Update: i called in a favour and got a windows binary, let me know if it works https://github.com/PGG106/Primer/releases/tag/v1.0

**Comment by bagaturchess** [comment]
Thanks for the binary!
yes it works as console application, when I start it and type convert from.binpack to.bin.
When I type in command prompt  primer-1.0-avx2.exe convert from.binpack to.bin it also works.
Best regards,
Krasimir

**Comment by bagaturchess** [comment]
Hi, I am closing the issue. Thanks!
Best regards,
Krasimir
