### ISSUE TITLE
Delete temp files after copying them

### ISSUE THREAD

**Issue by bagaturchess** [PGG106/Primer#2]
Hi,

this is just a proposal to delete each temp file immediately after copying it into the target output file.
In this way half of the disk space will be necessary.

I faced this issue, because my disk is not big enough for the data I am processing.
As a solution for me I concatenate the files into the tmp directory manually after deleting the input file.
I think this could be a nice improvement.

Best regards,
Krasimir

**Comment by PGG106** [comment]
Hi, when using the program locally i can notice the parsed bin file being converted, i don't really see any temp file being used, where exactly do they appear for you? this is a rough adaptation of some stockfish code and i can't really see anything about temp files

**Comment by bagaturchess** [comment]
Hi and sorry, I have reported the issue on the wrong place, it is about bullet utils when shuffling files.
Best regards,
Krasimir
